import { ExternalSourceEntity } from '../types';

export const MOCK_CANADA: Record<string, ExternalSourceEntity[]> = {
  law: [
    {
      id: 'CAN-STAT-PIPEDA',
      provider: 'justice-laws',
      entityType: 'law',
      displayMode: 'callout',
      sourceId: 'CAN-STAT-PIPEDA',
      title: 'Personal Information Protection and Electronic Documents Act (PIPEDA / LPRPDE)',
      subtitle: 'Department of Justice Canada · S.C. 2000, c. 5',
      status: 'valid',
      statusLabel: 'In force / En vigueur',
      statusColor: 'green',
      statusBadgeColor: 'success',
      borderColor: '#D32F2F',
      meta1: 'Citation : S.C. 2000, c. 5',
      meta2: 'Minister : Innovation, Science & Industry',
      meta3: 'Jurisdiction : Federal (Canada)',
      excerpt:
        'The purpose of this Part is to extend the present laws of Canada to protect the privacy of individuals with respect to personal information about themselves held by government institutions.',
      summary: 'Federal statute protecting personal information and electronic documents in Canadian commercial activities.',
      url: 'https://laws-lois.justice.gc.ca/eng/acts/P-8.6/',
      verifiedAt: '18/09/2026',
    },
  ],
  company: [
    {
      id: 'CORP-CA-1234567-8',
      provider: 'corporations-canada',
      entityType: 'company',
      displayMode: 'card',
      sourceId: 'CORP-CA-1234567-8',
      title: 'Shared Services Canada / Services partagés Canada',
      subtitle: 'Government of Canada Agency · Ottawa, ON',
      status: 'valid',
      statusLabel: 'Active / En vigueur',
      statusColor: 'green',
      statusBadgeColor: 'success',
      borderColor: '#D32F2F',
      meta1: 'Corporation # : 1234567-8',
      meta2: 'Business # : 849201948',
      meta3: 'Governing Act : Financial Admin Act',
      summary: 'Federal agency delivering secure, modern and reliable digital infrastructure and telecommunication services across Canada.',
      url: 'https://ised-isde.canada.ca/cc/lgcy/fdrlCrpDtls.html?corpId=1234567',
      verifiedAt: '18/09/2026',
    },
  ],
  parliament: [
    {
      id: 'CAN-BILL-44-1-C27',
      provider: 'legisinfo',
      entityType: 'parliament',
      displayMode: 'callout',
      sourceId: 'CAN-BILL-44-1-C27',
      title: 'Bill C-27 — Digital Charter Implementation Act / Loi sur la charte numérique',
      subtitle: '44th Parliament, 1st Session · House of Commons Canada',
      status: 'pending',
      statusLabel: 'In Committee',
      statusColor: 'blue',
      statusBadgeColor: 'info',
      borderColor: '#D32F2F',
      meta1: 'Bill : C-27',
      meta2: 'Sponsor : Minister of Innovation',
      meta3: 'House of Commons',
      excerpt:
        'An Act to enact the Consumer Privacy Protection Act, the Personal Information and Data Protection Tribunal Act and the Artificial Intelligence and Data Act.',
      summary: 'Federal legislation modernizing consumer privacy protection and artificial intelligence regulation in Canada.',
      url: 'https://www.parl.ca/legisinfo/en/bill/44-1/c-27',
      verifiedAt: '18/09/2026',
    },
  ],
  statistics: [
    {
      id: 'STATCAN-CPI-18100004',
      provider: 'statcan',
      entityType: 'statistics',
      displayMode: 'card',
      sourceId: 'STATCAN-CPI-18100004',
      title: 'Consumer Price Index (CPI) Canada — Annual Inflation Rate',
      subtitle: 'Statistics Canada · Web Data Service (WDS API)',
      status: 'valid',
      statusLabel: 'Official StatCan Data',
      statusColor: 'blue',
      statusBadgeColor: 'info',
      borderColor: '#D32F2F',
      meta1: 'All-items CPI : +2.5%',
      meta2: 'Geography : Canada',
      meta3: 'Table : 18-10-0004-01',
      excerpt:
        'The Consumer Price Index (CPI) represents changes in consumer prices experienced by Canadians over time.',
      summary: 'Official Canadian inflation index and monthly consumer price indicators.',
      url: 'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000401',
      verifiedAt: '18/09/2026',
    },
  ],
  opendata: [
    {
      id: 'OPEN-CAN-DS-GEO-2026',
      provider: 'opencanada',
      entityType: 'opendata',
      displayMode: 'card',
      sourceId: 'OPEN-CAN-DS-GEO-2026',
      title: 'National Road Network (NRN) GeoBase Canada — Open Data',
      subtitle: 'Natural Resources Canada · Open Government Portal (CKAN)',
      status: 'valid',
      statusLabel: 'OGL - Canada',
      statusColor: 'blue',
      statusBadgeColor: 'info',
      borderColor: '#D32F2F',
      meta1: 'Format : GeoJSON, SHP',
      meta2: 'Publisher : NRCan',
      meta3: 'Coverage : Pan-Canadian',
      summary: 'Authoritative open geographic geospatial dataset of Canadian roads and public transit infrastructure.',
      url: 'https://open.canada.ca/data/en/dataset/3d371465-762b-42ea-ac8f-3e3f42f3c001',
      verifiedAt: '18/09/2026',
    },
  ],
  procurement: [
    {
      id: 'CANADABUYS-WS428901',
      provider: 'canadabuys',
      entityType: 'procurement',
      displayMode: 'card',
      sourceId: 'CANADABUYS-WS428901',
      title: 'Federal Sovereign Cloud & Digital Workspace Infrastructure Procurement',
      subtitle: 'Public Services and Procurement Canada (PSPC / SPAC)',
      status: 'pending',
      statusLabel: 'Active Tender',
      statusColor: 'blue',
      statusBadgeColor: 'info',
      borderColor: '#D32F2F',
      meta1: 'Solicitation : WS428901',
      meta2: 'Buyer : Shared Services Canada',
      meta3: 'Closing : 2026-12-15',
      summary: 'Public tender for sovereign cloud hosting, collaborative office software, and secure enterprise identity.',
      url: 'https://canadabuys.canada.ca',
      verifiedAt: '18/09/2026',
    },
  ],
  place: [
    {
      id: 'GEO-CA-FDZCS',
      provider: 'geonames-ca',
      entityType: 'place',
      displayMode: 'card',
      sourceId: 'GEO-CA-FDZCS',
      title: 'Ottawa, Ontario (National Capital of Canada)',
      subtitle: 'Natural Resources Canada · Canadian Geographical Names Database (CGNDB)',
      status: 'valid',
      statusLabel: 'Official Name',
      statusColor: 'green',
      statusBadgeColor: 'success',
      borderColor: '#D32F2F',
      meta1: 'CGNDB Key : FDZCS',
      meta2: 'Province : Ontario (ON)',
      meta3: 'GPS : 45.4215° N, 75.6972° W',
      summary: 'Official geographic record for the city of Ottawa, national capital of Canada.',
      url: 'https://geonames.nrcan.gc.ca',
      verifiedAt: '18/09/2026',
    },
  ],
};
