import { ExternalSourceEntity } from '../types';

export const MOCK_EUROPE: Record<string, ExternalSourceEntity[]> = {
  law: [
    {
      id: 'CELEX-32016R0679',
      provider: 'eur-lex',
      entityType: 'law',
      displayMode: 'callout',
      sourceId: 'CELEX-32016R0679',
      title: 'Regulation (EU) 2016/679 (General Data Protection Regulation — GDPR)',
      subtitle: 'European Parliament and Council · Official Journal L 119',
      status: 'valid',
      statusLabel: 'In force',
      statusColor: 'green',
      statusBadgeColor: 'success',
      borderColor: '#003399',
      meta1: 'CELEX : 32016R0679',
      meta2: 'Applicable since 25/05/2018',
      meta3: 'EU Data Protection',
      excerpt:
        'The protection of natural persons in relation to the processing of personal data is a fundamental right. Article 8(1) of the Charter of Fundamental Rights of the European Union and Article 16(1) of the Treaty on the Functioning of the European Union (TFEU) provide that everyone has the right to the protection of personal data concerning him or her.',
      summary: 'Comprehensive European Union framework governing the processing and free movement of personal data.',
      url: 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
      verifiedAt: '17/09/2026',
    },
    {
      id: 'CELEX-32022L2555',
      provider: 'eur-lex',
      entityType: 'law',
      displayMode: 'callout',
      sourceId: 'CELEX-32022L2555',
      title: 'Directive (EU) 2022/2555 on measures for a high common level of cybersecurity across the Union (NIS 2)',
      subtitle: 'Official Journal L 333 · Transposition deadline: 17/10/2024',
      status: 'valid',
      statusLabel: 'In force',
      statusColor: 'green',
      statusBadgeColor: 'success',
      borderColor: '#003399',
      meta1: 'CELEX : 32022L2555',
      meta2: 'Cybersecurity Directive',
      meta3: 'Scope: Critical Infrastructure',
      excerpt:
        'This Directive lays down obligations on Member States regarding national cybersecurity strategies, national competent authorities, single points of contact, and computer security incident response teams (CSIRTs).',
      summary: 'Strengthens cybersecurity resilience across essential and important public and private entities in the EU.',
      url: 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
      verifiedAt: '17/09/2026',
    },
  ],
  procurement: [
    {
      id: 'TED-2026-S-084-129481',
      provider: 'ted',
      entityType: 'procurement',
      displayMode: 'card',
      sourceId: 'TED-2026-S-084-129481',
      title: 'European Sovereign Cloud Infrastructure & Collaborative Digital Workspace Services',
      subtitle: 'European Commission — Directorate-General for Digital Services (DIGIT)',
      status: 'pending',
      statusLabel: 'Open Call for Tenders',
      statusColor: 'blue',
      statusBadgeColor: 'info',
      borderColor: '#003399',
      meta1: 'Notice : 2026/S 084-129481',
      meta2: 'Value : €45,000,000',
      meta3: 'Deadline : 15/12/2026',
      excerpt:
        'Provision of open-source sovereign collaborative office tools, high-security WebRTC conferencing, and encrypted real-time document editing for European Institutions.',
      summary: 'Pan-European procurement for open source public digital infrastructure.',
      url: 'https://ted.europa.eu/en/notice/-/detail/129481-2026',
      verifiedAt: '17/09/2026',
    },
  ],
};
