import { ExternalSourceEntity } from '../types';

export const MOCK_EUROPE: Record<string, ExternalSourceEntity[]> = {
  law: [
    {
      id: 'CELEX-32016R0679',
      provider: 'eur-lex',
      entityType: 'law',
      displayMode: 'callout',
      sourceId: 'CELEX-32016R0679',
      title: 'Regulation (EU) 2016/679 (General Data Protection Regulation — GDPR)',
      subtitle: 'European Parliament and Council · Official Journal L 119',
      status: 'valid',
      statusLabel: 'In force',
      statusColor: 'green',
      statusBadgeColor: 'success',
      borderColor: '#003399',
      meta1: 'CELEX : 32016R0679',
      meta2: 'Applicable since 25/05/2018',
      meta3: 'EU Data Protection',
      excerpt:
        'The protection of natural persons in relation to the processing of personal data is a fundamental right. Article 8(1) of the Charter of Fundamental Rights of the European Union and Article 16(1) of the Treaty on the Functioning of the European Union (TFEU) provide that everyone has the right to the protection of personal data concerning him or her.',
      summary: 'Comprehensive European Union framework governing the processing and free movement of personal data.',
      url: 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
      verifiedAt: '17/09/2026',
    },
    {
      id: 'CELEX-32022L2555',
      provider: 'eur-lex',
      entityType: 'law',
      displayMode: 'callout',
      sourceId: 'CELEX-32022L2555',
      title: 'Directive (EU) 2022/2555 on measures for a high common level of cybersecurity across the Union (NIS 2)',
      subtitle: 'Official Journal L 333 · Transposition deadline: 17/10/2024',
      status: 'valid',
      statusLabel: 'In force',
      statusColor: 'green',
      statusBadgeColor: 'success',
      borderColor: '#003399',
      meta1: 'CELEX : 32022L2555',
      meta2: 'Cybersecurity Directive',
      meta3: 'Scope: Critical Infrastructure',
      excerpt:
        'This Directive lays down obligations on Member States regarding national cybersecurity strategies, national competent authorities, single points of contact, and computer security incident response teams (CSIRTs).',
      summary: 'Strengthens cybersecurity resilience across essential and important public and private entities in the EU.',
      url: 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
      verifiedAt: '17/09/2026',
    },
  ],
  procurement: [
    {
      id: 'TED-2026-S-084-129481',
      provider: 'ted',
      entityType: 'procurement',
      displayMode: 'card',
      sourceId: 'TED-2026-S-084-129481',
      title: 'European Sovereign Cloud Infrastructure & Collaborative Digital Workspace Services',
      subtitle: 'European Commission — Directorate-General for Digital Services (DIGIT)',
      status: 'pending',
      statusLabel: 'Open Call for Tenders',
      statusColor: 'blue',
      statusBadgeColor: 'info',
      borderColor: '#003399',
      meta1: 'Notice : 2026/S 084-129481',
      meta2: 'Value : €45,000,000',
      meta3: 'Deadline : 15/12/2026',
      excerpt:
        'Provision of open-source sovereign collaborative office tools, high-security WebRTC conferencing, and encrypted real-time document editing for European Institutions.',
      summary: 'Pan-European procurement for open source public digital infrastructure.',
      url: 'https://ted.europa.eu/en/notice/-/detail/129481-2026',
      verifiedAt: '17/09/2026',
    },
  ],
  parliament: [
    {
      id: 'EP-10-TA-2026-0042',
      provider: 'europarl',
      entityType: 'parliament',
      displayMode: 'callout',
      sourceId: 'EP-10-TA-2026-0042',
      title: 'European Parliament Resolution on Open Source Software & Digital Sovereignty',
      subtitle: '10th Parliamentary Term · Plenary Session Strasbourg',
      status: 'valid',
      statusLabel: 'Adopted',
      statusColor: 'green',
      statusBadgeColor: 'success',
      borderColor: '#003399',
      meta1: 'Committee : ITRE',
      meta2: 'Rapporteur : Industry & Energy Committee',
      meta3: 'Vote : 542 For, 48 Against',
      excerpt:
        'Calls on the Commission and Member States to systematically prioritize open-source solutions and European interoperable digital commons in public procurement.',
      summary: 'Parliamentary resolution endorsing open digital infrastructure across all EU Member States.',
      url: 'https://data.europarl.europa.eu/en/developer-corner',
      verifiedAt: '18/09/2026',
    },
  ],
  statistics: [
    {
      id: 'EUROSTAT-PRC-HICP-2026',
      provider: 'eurostat',
      entityType: 'statistics',
      displayMode: 'card',
      sourceId: 'EUROSTAT-PRC-HICP-2026',
      title: 'Eurostat Key Economic Indicator — Harmonised Index of Consumer Prices (HICP)',
      subtitle: 'European Statistical System · Monthly Dissemination API',
      status: 'valid',
      statusLabel: 'Official EU Data',
      statusColor: 'blue',
      statusBadgeColor: 'info',
      borderColor: '#003399',
      meta1: 'Euro Area : 2.1%',
      meta2: 'EU27 : 2.3%',
      meta3: 'Period : August 2026',
      excerpt:
        'Euro area annual inflation is estimated to be 2.1% in August 2026, according to a flash estimate from Eurostat, the statistical office of the European Union.',
      summary: 'Monthly consumer price inflation statistics harmonized across EU Member States.',
      url: 'https://ec.europa.eu/eurostat',
      verifiedAt: '18/09/2026',
    },
  ],
  grant: [
    {
      id: 'EU-CALL-HORIZON-CL4-2026-DIGITAL',
      provider: 'funding-tenders',
      entityType: 'grant',
      displayMode: 'card',
      sourceId: 'EU-CALL-HORIZON-CL4-2026-DIGITAL',
      title: 'Horizon Europe — Next Generation Sovereign Open Source Cloud & Digital Commons',
      subtitle: 'European Commission — DG CNECT · Call HORIZON-CL4-2026',
      status: 'valid',
      statusLabel: 'Open for Submission',
      statusColor: 'green',
      statusBadgeColor: 'success',
      borderColor: '#003399',
      meta1: 'Topic : HORIZON-CL4-2026-DATA-01',
      meta2: 'Budget : €50,000,000',
      meta3: 'Deadline : 18/11/2026',
      excerpt:
        'Grants supporting European collaborative consortia developing verified, open-source sovereign software, verifiable AI algorithms, and decentralized data spaces.',
      summary: 'European research grant program for open digital commons and sovereign technologies.',
      url: 'https://ec.europa.eu/info/funding-tenders/opportunities/portal',
      verifiedAt: '18/09/2026',
    },
  ],
  opendata: [
    {
      id: 'DATAEUROPA-DS-NUTS-2026',
      provider: 'dataeuropa',
      entityType: 'opendata',
      displayMode: 'card',
      sourceId: 'DATAEUROPA-DS-NUTS-2026',
      title: 'NUTS — Nomenclature of Territorial Units for Statistics (European Regions)',
      subtitle: 'Eurostat / Publications Office · DCAT-AP Catalog',
      status: 'valid',
      statusLabel: 'Open Access (CC-BY 4.0)',
      statusColor: 'blue',
      statusBadgeColor: 'info',
      borderColor: '#003399',
      meta1: 'Format : GeoJSON, TopoJSON',
      meta2: 'Publisher : European Commission',
      meta3: 'Scope : 27 EU Member States',
      excerpt:
        'Authoritative hierarchical classification of administrative and statistical regions in the European Union, maintained under open public license.',
      summary: 'Official geographic boundary datasets for statistical analysis and spatial modeling in the EU.',
      url: 'https://data.europa.eu',
      verifiedAt: '18/09/2026',
    },
  ],
  agent: [
    {
      id: 'WHOISWHO-EC-SG',
      provider: 'whoiswho',
      entityType: 'agent',
      displayMode: 'card',
      sourceId: 'WHOISWHO-EC-SG',
      title: 'European Commission — Secretariat-General (SG)',
      subtitle: 'European Commission · Official Directory',
      status: 'valid',
      statusLabel: 'Official Service',
      statusColor: 'blue',
      statusBadgeColor: 'info',
      borderColor: '#003399',
      meta1: 'Location : Brussels, Belgium',
      meta2: 'Director-General : Ilze Juhansone',
      meta3: 'Scope : Coordination',
      summary: 'Central department managing overall strategy and policy coordination across European Commission Directorates-General.',
      url: 'https://op.europa.eu/en/web/who-is-who',
      verifiedAt: '18/09/2026',
    },
  ],
  'case-law': [
    {
      id: 'ECLI:EU:C:2024:42',
      provider: 'curia',
      entityType: 'case-law',
      displayMode: 'callout',
      sourceId: 'ECLI:EU:C:2024:42',
      title: 'Judgment of the Court (Grand Chamber) — Case C-42/24 (GDPR & Data Protection)',
      subtitle: 'Court of Justice of the European Union (CJUE) · Luxembourg',
      status: 'valid',
      statusLabel: 'Final Judgment',
      statusColor: 'green',
      statusBadgeColor: 'success',
      borderColor: '#003399',
      meta1: 'Case : C-42/24',
      meta2: 'ECLI : ECLI:EU:C:2024:42',
      meta3: 'Date : 14/06/2024',
      excerpt:
        'Article 6(1) of Regulation (EU) 2016/679 must be interpreted as precluding the processing of personal data by public authorities in the absence of a clear and accessible legal basis.',
      summary: 'CJEU landmark judgment on legal grounds for personal data processing under GDPR.',
      url: 'https://curia.europa.eu',
      verifiedAt: '18/09/2026',
    },
  ],
  research: [
    {
      id: 'CORDIS-HORIZON-101042',
      provider: 'cordis',
      entityType: 'research',
      displayMode: 'card',
      sourceId: 'CORDIS-HORIZON-101042',
      title: 'OpenSovereignAI — Verified Open Source AI Models for European Public Services',
      subtitle: 'Horizon Europe Research Project · Grant 101042',
      status: 'valid',
      statusLabel: 'Ongoing Project',
      statusColor: 'blue',
      statusBadgeColor: 'info',
      borderColor: '#003399',
      meta1: 'EU Contribution : €4,500,000',
      meta2: 'Programme : Horizon Europe',
      meta3: 'Period : 2024-2027',
      excerpt:
        'Consortium project delivering transparent, audit-ready open-weights AI models, federated RAG retrieval, and multi-lingual conversational agents.',
      summary: 'EU-funded research initiative under Horizon Europe for open public digital infrastructure.',
      url: 'https://cordis.europa.eu',
      verifiedAt: '18/09/2026',
    },
  ],
};
