import { ExternalSourceEntity } from '../types';

export const MOCK_FRANCE: Record<string, ExternalSourceEntity[]> = {
  law: [
    {
      id: 'LEGIARTI000037812976',
      provider: 'legifrance',
      entityType: 'law',
      displayMode: 'callout',
      sourceId: 'LEGIARTI000037812976',
      title: 'Article L. 111-1 du Code de la commande publique',
      subtitle: 'Code de la commande publique - Partie législative',
      status: 'valid',
      statusLabel: 'En vigueur',
      statusColor: 'green',
      statusBadgeColor: 'success',
      borderColor: '#000091',
      meta1: 'LEGIARTI000037812976',
      meta2: 'Ordonnance n° 2018-1074',
      meta3: 'Entrée en vigueur : 01/04/2019',
      excerpt:
        'Un marché est un contrat conclu par un ou plusieurs acheteurs soumis au présent code avec un ou plusieurs opérateurs économiques, pour répondre à leurs besoins en matière de travaux, de fournitures ou de services, en contrepartie d’un prix ou de tout équivalent.',
      summary:
        'Définit la notion fondamentale de marché public et ses conditions d’application.',
      url: 'https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000037812976',
      verifiedAt: '17/09/2026',
    },
  ],
  company: [
    {
      id: '13002526500013',
      provider: 'rne',
      entityType: 'company',
      displayMode: 'card',
      sourceId: '13002526500013',
      title: 'Direction Interministérielle du Numérique (DINUM)',
      subtitle: 'Service du Premier ministre',
      status: 'valid',
      statusLabel: 'In Bonis (Actif)',
      statusColor: 'green',
      statusBadgeColor: 'success',
      borderColor: '#000091',
      meta1: 'SIREN : 130 025 265',
      meta2: 'NAF : 84.11Z (Administration publique générale)',
      meta3: 'Effectif : 250+ agents',
      summary:
        'Conçoit et met en œuvre la stratégie numérique de l’État français, garantit la souveraineté technologique et développe La Suite Numérique.',
      url: 'https://annuaire-entreprises.data.gouv.fr/entreprise/direction-interministerielle-du-numerique-dinum-130025265',
      verifiedAt: '17/09/2026',
    },
  ],
  parliament: [
    {
      id: 'AN-17-PJL-542-AMD-42',
      provider: 'assemblee-nationale',
      entityType: 'parliament',
      displayMode: 'callout',
      sourceId: 'AN-17-PJL-542-AMD-42',
      title: 'Amendement n° 42 au Projet de Loi Souveraineté Numérique',
      subtitle: '17ème Législature - Déposé le 12/09/2026',
      status: 'valid',
      statusLabel: 'Adopté en séance',
      statusColor: 'green',
      statusBadgeColor: 'success',
      borderColor: '#000091',
      meta1: 'Rapporteur : Commission des Lois',
      meta2: 'Séance n° 142',
      meta3: 'Scrutin public n° 88 (Pour: 340, Contre: 22)',
      excerpt:
        'Après l’article 4, insérer un article ainsi rédigé : Les administrations centrales recourent par priorité aux solutions logicielles souveraines et libres certifiées par l’Agence Nationale de la Sécurité des Systèmes d’Information.',
      summary: 'Obligation de priorité aux suites collaboratives ouvertes de l’État.',
      url: 'https://www.assemblee-nationale.fr/dyn/17/amendements/0542/42',
      verifiedAt: '17/09/2026',
    },
  ],
  address: [
    {
      id: 'ADR-75107-0020-0020',
      provider: 'ban',
      entityType: 'address',
      displayMode: 'link',
      sourceId: 'ADR-75107-0020-0020',
      title: '20 avenue de Ségur, 75007 Paris',
      subtitle: 'Site Ségur-Fontenoy (DINUM & Ministères Sociaux)',
      status: 'valid',
      statusLabel: 'BAN Certifiée',
      statusColor: 'green',
      statusBadgeColor: 'success',
      borderColor: '#000091',
      meta1: 'INSEE : 75107',
      meta2: 'GPS : 48.8504, 2.3082',
      meta3: 'Score de confiance : 0.98',
      summary: 'Siège de la Direction Interministérielle du Numérique (DINUM).',
      url: 'https://adresse.data.gouv.fr/base-adresse-nationale/75107_0020_00020#18/48.8504/2.3082',
      verifiedAt: '17/09/2026',
    },
  ],
  procurement: [
    {
      id: 'BOAMP-26-042819',
      provider: 'boamp',
      entityType: 'procurement',
      displayMode: 'card',
      sourceId: 'BOAMP-26-042819',
      title: "Fourniture et déploiement d'une infrastructure cloud souveraine",
      subtitle: 'Direction Interministérielle du Numérique (DINUM)',
      status: 'pending',
      statusLabel: 'Offres ouvertes',
      statusColor: 'blue',
      statusBadgeColor: 'info',
      borderColor: '#000091',
      meta1: 'AAPC n° 26-042819',
      meta2: 'Procédure adaptée (MAPA)',
      meta3: 'Clôture : 15/10/2026',
      excerpt:
        "Le présent marché a pour objet l'acquisition de prestations d'hébergement qualifié SecNumCloud pour les services interministériels de La Suite Numérique.",
      summary: 'Marché interministériel d’infrastructure cloud souveraine pour 250 000 agents de l’État.',
      url: 'https://www.boamp.fr/pages/avis/?q=idweb:26-042819',
      verifiedAt: '17/09/2026',
    },
  ],
};
