import { ExternalSourceEntity } from '../types';

export const MOCK_GERMANY: Record<string, ExternalSourceEntity[]> = {
  law: [
    {
      id: 'BGB-823',
      provider: 'gesetze-im-internet',
      entityType: 'law',
      displayMode: 'callout',
      sourceId: 'BGB-823',
      title: '§ 823 Bürgerliches Gesetzbuch (BGB) — Schadensersatzpflicht',
      subtitle: 'Bundesministerium der Justiz · Gesetze im Internet',
      status: 'valid',
      statusLabel: 'In Kraft',
      statusColor: 'green',
      statusBadgeColor: 'success',
      borderColor: '#000000',
      meta1: 'BGB § 823 Abs. 1',
      meta2: 'Fassung vom 02.01.2002',
      meta3: 'Zivilrecht',
      excerpt:
        'Wer vorsätzlich oder fahrlässig das Leben, den Körper, die Gesundheit, die Freiheit, das Eigentum oder ein sonstiges Recht eines anderen widerrechtlich verletzt, ist dem anderen zum Ersatz des daraus entstehenden Schadens verpflichtet.',
      summary: 'Grundlegende Haftungsnorm des deutschen Deliktsrechts für Schadensersatzansprüche.',
      url: 'https://www.gesetze-im-internet.de/bgb/__823.html',
      verifiedAt: '17/09/2026',
    },
  ],
  company: [
    {
      id: 'HRB-350269',
      provider: 'handelsregister',
      entityType: 'company',
      displayMode: 'card',
      sourceId: 'HRB-350269',
      title: 'SAP SE',
      subtitle: 'Amtsgericht Mannheim · Handelsregister B',
      status: 'valid',
      statusLabel: 'Aktiv (HRB)',
      statusColor: 'green',
      statusBadgeColor: 'success',
      borderColor: '#000000',
      meta1: 'HRB : 350269',
      meta2: 'Sitz : Walldorf (Baden-Württemberg)',
      meta3: 'Rechtsform : Europäische Aktiengesellschaft (SE)',
      summary:
        'Führender europäischer Entwickler von Unternehmenssoftware und Cloud-Technologien.',
      url: 'https://www.handelsregister.de/',
      verifiedAt: '17/09/2026',
    },
  ],
  procurement: [
    {
      id: 'EVERGABE-2026-89412',
      provider: 'evergabe',
      entityType: 'procurement',
      displayMode: 'card',
      sourceId: 'EVERGABE-2026-89412',
      title: 'Bereitstellung von Open-Source-Kollaborationsdiensten für Bundesbehörden',
      subtitle: 'Beschaffungsamt des Bundesministeriums des Innern (BMI)',
      status: 'pending',
      statusLabel: 'Offenes Verfahren',
      statusColor: 'blue',
      statusBadgeColor: 'info',
      borderColor: '#000000',
      meta1: 'Bekanntmachung : 2026-DE-89412',
      meta2: 'Frist : 28/10/2026',
      meta3: 'Bundesverwaltung',
      excerpt:
        'Öffentliche Ausschreibung über die Bereitstellung, Härtung und den 24/7-Betrieb von sicheren Cloud-Arbeitsplätzen für Bundes- und Landesbehörden.',
      summary: 'Bundesweite Vergabe für interoperable und quelloffene Softwareinfrastrukturen.',
      url: 'https://www.evergabe-online.de/',
      verifiedAt: '17/09/2026',
    },
  ],
};
