import { ExternalSourceEntity } from '../types';

export const MOCK_NETHERLANDS: Record<string, ExternalSourceEntity[]> = {
  law: [
    {
      id: 'BW6-162',
      provider: 'overheid-nl',
      entityType: 'law',
      displayMode: 'callout',
      sourceId: 'BW6-162',
      title: 'Artikel 6:162 Burgerlijk Wetboek (BW) — Onrechtmatige daad',
      subtitle: 'Wettenbank · Rijksoverheid (Overheid.nl)',
      status: 'valid',
      statusLabel: 'Geldend',
      statusColor: 'green',
      statusBadgeColor: 'success',
      borderColor: '#FF6600',
      meta1: 'BW Boek 6, Art. 162',
      meta2: 'Geldend vanaf 01-01-1992',
      meta3: 'Verbintenissenrecht',
      excerpt:
        'Hij die jegens een ander een onrechtmatige daad pleegt, welke hem kan worden toegerekend, is verplicht de schade die de ander dientengevolge lijdt, te vergoeden.',
      summary: 'Fundamentele bepaling in het Nederlandse aansprakelijkheidsrecht.',
      url: 'https://wetten.overheid.nl/BWBR0005289/',
      verifiedAt: '17/09/2026',
    },
  ],
  company: [
    {
      id: 'KVK-17085892',
      provider: 'kvk',
      entityType: 'company',
      displayMode: 'card',
      sourceId: 'KVK-17085892',
      title: 'ASML Holding N.V.',
      subtitle: 'Kamer van Koophandel (KvK) Handelsregister',
      status: 'valid',
      statusLabel: 'Actief (KvK)',
      statusColor: 'green',
      statusBadgeColor: 'success',
      borderColor: '#FF6600',
      meta1: 'KvK-nummer : 17085892',
      meta2: 'Vestigingsplaats : Veldhoven',
      meta3: 'Rechtsvorm : Naamloze Vennootschap (N.V.)',
      summary:
        'Wereldwijd toonaangevende leverancier van fotolithografiesystemen voor de halfgeleiderindustrie.',
      url: 'https://www.kvk.nl/bestellen/#/17085892',
      verifiedAt: '17/09/2026',
    },
  ],
  procurement: [
    {
      id: 'TENDER-NL-2026-4412',
      provider: 'tenderned',
      entityType: 'procurement',
      displayMode: 'card',
      sourceId: 'TENDER-NL-2026-4412',
      title: 'Open Source Werkplekomgeving Rijksoverheid',
      subtitle: 'Ministerie van Binnenlandse Zaken en Koninkrijksrelaties (BZK)',
      status: 'pending',
      statusLabel: 'Aanbesteding geopend',
      statusColor: 'blue',
      statusBadgeColor: 'info',
      borderColor: '#FF6600',
      meta1: 'Kenmerk : NL-2026-4412',
      meta2: 'Sluitingsdatum : 20/11/2026',
      meta3: 'Europese procedure',
      excerpt:
        'Aanbesteding voor de implementatie en ondersteuning van soevereine en interoperabele samenwerkingssoftware voor de centrale overheid.',
      summary: 'Landelijke overheidsaanbesteding voor digitale soevereiniteit.',
      url: 'https://www.tenderned.nl/',
      verifiedAt: '17/09/2026',
    },
  ],
};
