import { ExternalSourceEntity } from '../types';

export const MOCK_SPAIN: Record<string, ExternalSourceEntity[]> = {
  law: [
    {
      id: 'BOE-A-2018-16673',
      provider: 'boe',
      entityType: 'law',
      displayMode: 'callout',
      sourceId: 'BOE-A-2018-16673',
      title: 'Ley Orgánica 3/2018 de Protección de Datos Personales (LOPDGDD)',
      subtitle: 'Boletín Oficial del Estado (BOE)',
      status: 'valid',
      statusLabel: 'En vigor',
      statusColor: 'green',
      statusBadgeColor: 'success',
      borderColor: '#AA151B',
      meta1: 'BOE-A-2018-16673',
      meta2: 'Disposición general n° 16673',
      meta3: 'Entrada en vigor : 07/12/2018',
      excerpt:
        'El tratamiento de los datos personales de un menor de edad únicamente podrá fundarse en su consentimiento cuando sea mayor de catorce años.',
      summary:
        'Adapta el ordenamiento jurídico español al Reglamento (UE) 2016/679 (RGPD) y garantiza los derechos digitales.',
      url: 'https://www.boe.es/buscar/act.php?id=BOE-A-2018-16673',
      verifiedAt: '17/09/2026',
    },
  ],
  company: [
    {
      id: 'ESA28015865',
      provider: 'registro-mercantil',
      entityType: 'company',
      displayMode: 'card',
      sourceId: 'ESA28015865',
      title: 'Telefónica, S.A.',
      subtitle: 'Registro Mercantil de Madrid',
      status: 'valid',
      statusLabel: 'Activa (In Bonis)',
      statusColor: 'green',
      statusBadgeColor: 'success',
      borderColor: '#AA151B',
      meta1: 'CIF : A-28015865',
      meta2: 'CNAE : 6110 (Telecomunicaciones por cable)',
      meta3: 'Sede : Distrito Telefónica, Madrid',
      summary:
        'Empresa multinacional española de telecomunicaciones e infraestructuras digitales.',
      url: 'https://www.registradores.org/',
      verifiedAt: '17/09/2026',
    },
  ],
  procurement: [
    {
      id: 'ES-PLACSP-2026-8812',
      provider: 'contratacion-del-estado',
      entityType: 'procurement',
      displayMode: 'callout',
      sourceId: 'ES-PLACSP-2026-8812',
      title: 'Despliegue de Infraestructura Cloud Pública Soberana',
      subtitle: 'Secretaría General de Administración Digital (SGAD)',
      status: 'pending',
      statusLabel: 'En licitación',
      statusColor: 'blue',
      statusBadgeColor: 'info',
      borderColor: '#AA151B',
      meta1: 'Expediente : SGAD-2026-CLOUD',
      meta2: 'Presupuesto : 14.200.000 €',
      meta3: 'Cierre de ofertas : 15/10/2026',
      excerpt:
        'Adquisición de servicios cloud soberanos certificados por el Esquema Nacional de Seguridad (ENS Nivel Alto).',
      summary:
        'Licitación pública para la modernización de servicios digitales de la Administración General del Estado.',
      url: 'https://contrataciondelestado.es/',
      verifiedAt: '17/09/2026',
    },
  ],
  cadastre: [
    {
      id: 'ES-CAT-28900A01200044',
      provider: 'sede-catastro',
      entityType: 'cadastre',
      displayMode: 'card',
      sourceId: 'ES-CAT-28900A01200044',
      title: 'Parcela Urbana 28900A01200044',
      subtitle: 'Dirección General del Catastro (Ministerio de Hacienda)',
      status: 'valid',
      statusLabel: 'Registrada',
      statusColor: 'green',
      statusBadgeColor: 'success',
      borderColor: '#AA151B',
      meta1: 'Ref. Catastral : 28900A012000440000AB',
      meta2: 'Superficie : 1.450 m²',
      meta3: 'Uso principal : Residencial',
      summary: 'Finca catastral certificada con delimitación gráfica georreferenciada.',
      url: 'https://www.sedecatastro.gob.es/',
      verifiedAt: '17/09/2026',
    },
  ],
};
