import { SourceEntityProps, SourceEntityType } from './types';

export const MOCK_SOURCES: Partial<Record<SourceEntityType, SourceEntityProps[]>> = {
  law: [
    {
      entityType: 'law',
      displayMode: 'callout',
      sourceId: 'LEGIARTI000037812976',
      title: 'Article L. 111-1 du Code de la commande publique',
      subtitle: 'Code de la commande publique - Partie législative',
      status: 'En vigueur',
      statusColor: 'green',
      meta1: 'LEGIARTI000037812976',
      meta2: 'Ordonnance n° 2018-1074',
      meta3: 'Entrée en vigueur : 01/04/2019',
      excerpt:
        'Un marché est un contrat conclu par un ou plusieurs acheteurs soumis au présent code avec un ou plusieurs opérateurs économiques, pour répondre à leurs besoins en matière de travaux, de fournitures ou de services, en contrepartie d’un prix ou de tout équivalent.',
      summary:
        'Définit la notion fondamentale de marché public et ses conditions d’application.',
      url: 'https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000037812976',
      verifiedAt: '17/09/2026',
    },
  ],
  company: [
    {
      entityType: 'company',
      displayMode: 'card',
      sourceId: '13002526500013',
      title: 'Direction Interministérielle du Numérique (DINUM)',
      subtitle: 'Service du Premier ministre',
      status: 'In Bonis (Actif)',
      statusColor: 'green',
      meta1: 'SIREN : 130 025 265',
      meta2: 'NAF : 84.11Z (Administration publique générale)',
      meta3: 'Effectif : 250+ agents',
      summary:
        'Conçoit et met en œuvre la stratégie numérique de l’État français, garantit la souveraineté technologique et développe La Suite Numérique.',
      url: 'https://annuaire-entreprises.data.gouv.fr/entreprise/direction-interministerielle-du-numerique-dinum-130025265',
      verifiedAt: '17/09/2026',
    },
  ],
  parliament: [
    {
      entityType: 'parliament',
      displayMode: 'callout',
      sourceId: 'AN-17-PJL-542-AMD-42',
      title: 'Amendement n° 42 au Projet de Loi Souveraineté Numérique',
      subtitle: '17ème Législature - Déposé le 12/09/2026',
      status: 'Adopté en séance',
      statusColor: 'green',
      meta1: 'Rapporteur : Commission des Lois',
      meta2: 'Séance n° 142',
      meta3: 'Scrutin public n° 88 (Pour: 340, Contre: 22)',
      excerpt:
        'Après l’article 4, insérer un article ainsi rédigé : Les administrations centrales recourent par priorité aux solutions logicielles souveraines et libres certifiées par l’Agence Nationale de la Sécurité des Systèmes d’Information.',
      summary: 'Obligation de priorité aux suites collaboratives ouvertes de l’État.',
      url: 'https://www.assemblee-nationale.fr/dyn/17/amendements/0542/42',
      verifiedAt: '17/09/2026',
    },
  ],
  address: [
    {
      entityType: 'address',
      displayMode: 'card',
      sourceId: 'ADR-75107-0020-0020',
      title: '20 avenue de Ségur, 75007 Paris',
      subtitle: 'Site Ségur-Fontenoy (DINUM & Ministères Sociaux)',
      status: 'BAN Certifiée',
      statusColor: 'green',
      meta1: 'INSEE : 75107',
      meta2: 'GPS : 48.8504, 2.3082',
      meta3: 'Score de confiance : 0.98',
      summary: 'Siège de la Direction Interministérielle du Numérique (DINUM).',
      url: 'https://adresse.data.gouv.fr/base-adresse-nationale/75107_0020_00020#18/48.8504/2.3082',
      verifiedAt: '17/09/2026',
    },
  ],
  procurement: [
    {
      entityType: 'procurement',
      displayMode: 'card',
      sourceId: 'BOAMP-26-042819',
      title: "Fourniture et déploiement d'une infrastructure cloud souveraine",
      subtitle: 'Direction Interministérielle du Numérique (DINUM)',
      status: 'Offres ouvertes',
      statusColor: 'blue',
      meta1: 'AAPC n° 26-042819',
      meta2: 'Procédure adaptée (MAPA)',
      meta3: 'Clôture : 15/10/2026',
      excerpt:
        "Le présent marché a pour objet l'acquisition de prestations d'hébergement qualifié SecNumCloud pour les services interministériels de La Suite Numérique.",
      summary: 'Marché interministériel d’infrastructure cloud souveraine pour 250 000 agents de l’État.',
      url: 'https://www.boamp.fr/pages/avis/?q=idweb:26-042819',
      verifiedAt: '17/09/2026',
    },
  ],
  grant: [
    {
      entityType: 'grant',
      displayMode: 'card',
      sourceId: 'AIDE-ANCT-FV-2026-01',
      title: 'Fonds Vert — Rénovation énergétique des bâtiments publics locaux',
      subtitle: 'Ministère de la Transition Écologique & ANCT',
      status: 'Candidatures ouvertes',
      statusColor: 'green',
      meta1: 'Financeur : Fonds Vert',
      meta2: 'Taux max : 80%',
      meta3: 'Clôture : 31/12/2026',
      excerpt:
        'Aide financière destinée aux collectivités territoriales pour financer les travaux de performance énergétique globale sur les écoles, mairies et équipements sportifs.',
      summary: 'Subvention d’État pour accélérer la décarbonation du patrimoine bâti public.',
      url: 'https://aides-territoires.beta.gouv.fr/aides/fonds-vert-renovation-batiments-publics/',
      verifiedAt: '17/09/2026',
    },
  ],
  insee: [
    {
      entityType: 'insee',
      displayMode: 'card',
      sourceId: 'INSEE-COM-75056',
      title: 'Chiffres clés de la Ville de Paris (75056)',
      subtitle: 'INSEE — Recensement de la Population (RP 2024)',
      status: 'Données Certifiées',
      statusColor: 'blue',
      meta1: 'Population : 2 133 111 hab.',
      meta2: 'Densité : 20 238 hab./km²',
      meta3: 'Emplois : 1 842 500',
      excerpt:
        'Paris concentre 17,2% des emplois de la région Île-de-France avec un taux d’activité des 15-64 ans s’élevant à 78,4%.',
      summary: 'Statistiques officielles de population et d’emploi produites par l’INSEE.',
      url: 'https://www.insee.fr/fr/statistiques/zones/75056',
      verifiedAt: '17/09/2026',
    },
  ],
  agent: [
    {
      entityType: 'agent',
      displayMode: 'card',
      sourceId: 'AGENT-DINUM-DIR',
      title: 'Direction Interministérielle du Numérique (DINUM)',
      subtitle: 'Services du Premier ministre',
      status: 'Annuaire Certifié DILA',
      statusColor: 'blue',
      meta1: 'Courriel : contact@numerique.gouv.fr',
      meta2: 'Tél : 01 71 21 00 00',
      meta3: '20 avenue de Ségur, 75007 Paris',
      summary: 'Service public central de pilotage de la transformation numérique de l’État.',
      url: 'https://lannuaire.service-public.fr',
      verifiedAt: '17/09/2026',
    },
  ],
  cadastre: [
    {
      entityType: 'cadastre',
      displayMode: 'card',
      sourceId: 'CAD-75107-AK-0042',
      title: 'Parcelle Section AK n° 0042 (Paris 7e)',
      subtitle: 'DGFiP / IGN — Commune de Paris 7e',
      status: 'Cadastre Certifié DGFiP',
      statusColor: 'green',
      meta1: 'Contenance : 14 520 m²',
      meta2: 'Feuille : 000 AK 01',
      meta3: 'Mise à jour : 01/01/2026',
      summary: 'Parcelle cadastrale officielle issue du plan cadastral vectoriel informatisé.',
      url: 'https://cadastre.data.gouv.fr',
      verifiedAt: '17/09/2026',
    },
  ],
  demarche: [
    {
      entityType: 'demarche',
      displayMode: 'card',
      sourceId: 'DS-PROC-84290',
      title: 'Demande d’habilitation aux services La Suite Numérique',
      subtitle: 'Direction Interministérielle du Numérique (DINUM)',
      status: 'Formulaire Actif',
      statusColor: 'green',
      meta1: 'Procédure n° 84290',
      meta2: 'Délai : 48h',
      meta3: 'Cible : Administrations',
      summary: 'Téléprocédure officielle de raccordement des ministères et administrations publiques.',
      url: 'https://www.demarches-simplifiees.fr',
      verifiedAt: '17/09/2026',
    },
  ],
  opendata: [
    {
      entityType: 'opendata',
      displayMode: 'card',
      sourceId: 'DATAGOUV-DS-6429',
      title: 'Base Sirene des entreprises et de leurs établissements',
      subtitle: 'data.gouv.fr — Ministère de l’Économie / INSEE',
      status: 'Licence Ouverte',
      statusColor: 'blue',
      meta1: 'Format : CSV, JSON, Parquet',
      meta2: 'Fréquence : Quotidienne',
      meta3: 'Téléchargements : 4.8M/mois',
      summary: 'Jeu de données de référence du service public de la donnée certifié par l’INSEE.',
      url: 'https://www.data.gouv.fr',
      verifiedAt: '17/09/2026',
    },
  ],
  custom: [
    {
      entityType: 'custom',
      displayMode: 'callout',
      sourceId: 'ALBERT-RAG-FP-001',
      title: "Préavis de démission d'un agent contractuel de la fonction publique",
      subtitle: 'Synthèse Albert (Décret n° 86-83 du 17 janvier 1986 - Art. 48)',
      status: 'Certifié Albert RAG',
      statusColor: 'purple',
      meta1: 'Source : DGAFP / Service-Public',
      meta2: 'Modèle : Albert-Large-Fr-v2',
      meta3: 'Confiance : 96%',
      excerpt:
        'L’agent contractuel qui démissionne doit respecter un préavis dont la durée varie selon son ancienneté : 8 jours (< 6 mois), 1 mois (6 mois à 2 ans), et 2 mois (>= 2 ans).',
      summary: 'Durée légale du préavis de démission applicable aux agents non titulaires.',
      url: 'https://albert.etalab.gouv.fr',
      verifiedAt: '17/09/2026',
    },
  ],
  statistics: [
    {
      entityType: 'statistics',
      displayMode: 'card',
      sourceId: 'STAT-EU-2026-001',
      title: 'Eurostat Key Indicators — GDP & Inflation',
      subtitle: 'European Statistical System (Eurostat SDMX)',
      status: 'Official Data',
      statusColor: 'blue',
      meta1: 'Inflation (HICP) : 2.1%',
      meta2: 'Zone : Euro Area (EA20)',
      meta3: 'Période : Q3 2026',
      excerpt: 'Official harmonized consumer price index and economic data released by Eurostat.',
      summary: 'Harmonized index of consumer prices across EU member states.',
      url: 'https://ec.europa.eu/eurostat',
      verifiedAt: '18/09/2026',
    },
  ],
  'case-law': [
    {
      entityType: 'case-law',
      displayMode: 'callout',
      sourceId: 'ECLI:EU:C:2024:42',
      title: 'Arrêt de la Cour (Grande chambre) — Protection des Données',
      subtitle: 'Cour de justice de l’Union européenne (CJUE)',
      status: 'Jurisprudence',
      statusColor: 'green',
      meta1: 'Affaire C-42/24',
      meta2: 'ECLI:EU:C:2024:42',
      meta3: 'Date : 14/06/2024',
      excerpt: 'L’article 6 du RGPD doit être interprété en ce sens qu’il s’oppose à un traitement de données personnelles sans base juridique valable.',
      summary: 'Portée du consentement et des bases légales de traitement de données au titre du RGPD.',
      url: 'https://curia.europa.eu',
      verifiedAt: '18/09/2026',
    },
  ],
  place: [
    {
      entityType: 'place',
      displayMode: 'card',
      sourceId: 'GEO-CA-OTTAWA',
      title: 'Ottawa, Ontario, Canada',
      subtitle: 'Canadian Geographical Names Database (CGNDB)',
      status: 'Verified Place',
      statusColor: 'green',
      meta1: 'CGNDB : FDZCS',
      meta2: 'Type : Capital City',
      meta3: 'GPS : 45.4215, -75.6972',
      summary: 'National capital of Canada located in Ontario.',
      url: 'https://geonames.nrcan.gc.ca',
      verifiedAt: '18/09/2026',
    },
  ],
  research: [
    {
      entityType: 'research',
      displayMode: 'card',
      sourceId: 'CORDIS-HORIZON-101042',
      title: 'Horizon Europe — Open Source Sovereign AI for Public Administrations',
      subtitle: 'European Commission (CORDIS)',
      status: 'Ongoing Project',
      statusColor: 'blue',
      meta1: 'Budget : 4.5M €',
      meta2: 'Programme : Horizon Europe',
      meta3: 'Fin : 2027',
      excerpt: 'Research project delivering verifiable and privacy-preserving AI models for EU public administrations.',
      summary: 'Co-funded research initiative under Digital Europe and Horizon Europe.',
      url: 'https://cordis.europa.eu',
      verifiedAt: '18/09/2026',
    },
  ],
};
